import 'assets/style.scss';
import 'assets/variables.scss';
import 'assets/fontawesome.css';
import 'components/logo/logo.scss';
import 'components/colors/colors.scss';
import 'components/type/type.scss';
import 'components/text/text.scss';
import 'components/form/form.scss';
import 'components/input/input.scss';
import 'components/dropdown/dropdown.scss';
import 'components/toggle/toggle.scss';
import 'components/radio/radio.scss';
import 'components/checkbox/checkbox.scss';
import 'components/like-btn/like-btn.scss';
import 'components/button/button.scss';
import 'components/range-slider/range-slider.scss';
import 'components/rate-btn/rate-btn.scss';
import 'components/pagination/pagination.scss';
import 'components/bullet-list/bullet-list.scss';
import 'components/review/review.scss';
import 'components/room-info/room-info.scss';
import 'components/checkbox-expandable/checkbox-expandable.scss';
import 'components/room-booking/room-booking.scss';
import 'components/login/login.scss';
import 'components/register/register.scss';
import 'components/search-room/search-room.scss';
import 'components/calendar/calendar.scss';
import 'components/room-cards/room-cards.scss';
import 'slick-carousel/slick/slick.scss'
import 'slick-carousel/slick/slick-theme.scss'
import 'components/header/header.scss'
import 'components/footer/footer.scss'
import 'components/footer-mini/footer-mini.scss'

require('jquery-ui-bundle');
require('slick-carousel');
import 'components/dropdown/dropdown-class';
import 'components/input/input';
import 'components/input/datepicker-ext';
import 'components/like-btn/like-btn';
import 'components/range-slider/range-slider';
import 'components/range-slider/jQueryUI-TouchPunch';
import 'components/rate-btn/star-rating-plugin';
import 'components/rate-btn/rate-btn';
import 'components/pagination/pagination-plugin';
import 'components/pagination/pagination';
import 'components/checkbox-expandable/checkbox-expandable';
import 'components/search-room/search-room';
import 'components/room-booking/room-booking';
import 'components/calendar/calendar';
import 'components/room-cards/room-cards';
import 'components/header/header'

