import 'assets/style.scss';
import 'assets/variables.scss';
import 'components/logo/logo.scss';
import 'components/colors/colors.scss';
import 'components/colors/__item/__item.scss';
import 'components/type/type.scss';
import 'components/heading/heading.scss';
import 'components/form/form.scss';
import 'components/input/input.scss';
import 'components/dropdown/dropdown.scss';
import 'components/toggle/toggle.scss';
import 'components/radio/radio.scss';
import 'components/checkbox/checkbox.scss';
import 'components/like-btn/like-btn.scss';
import 'components/button/button.scss';
import 'components/range-slider/range-slider.scss';
import 'components/rate-btn/rate-btn.scss';
import 'components/pagination/pagination.scss';

require('jquery-ui-bundle');
import 'components/dropdown/dropdown';
import 'components/input/input';
import 'components/input/datepicker-ext';
import 'components/like-btn/like-btn';
import 'components/range-slider/range-slider';
import 'components/range-slider/jQueryUI-TouchPunch';
import 'components/rate-btn/rate-btn';
import 'components/rate-btn/star-rating-plugin';
import 'components/pagination/pagination-plugin';
import 'components/pagination/pagination';

